#!/bin/bash
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PASS=0
FAIL=0

pass() { echo "[PASS] $1"; PASS=$((PASS + 1)); }
fail() { echo "[FAIL] $1"; FAIL=$((FAIL + 1)); }

require_file() {
    if [ -f "${SCRIPT_DIR}/$1" ]; then pass "$2"; else fail "$2"; fi
}

require_grep() {
    local pattern="$1" file="$2" label="$3"
    if grep -Eq -- "${pattern}" "${SCRIPT_DIR}/${file}"; then pass "${label}"; else fail "${label}"; fi
}

forbid_grep() {
    local pattern="$1" file="$2" label="$3"
    if grep -Eq -- "${pattern}" "${SCRIPT_DIR}/${file}"; then fail "${label}"; else pass "${label}"; fi
}

require_file "EMBEDDING_DESIGN.md" "embedding design contract exists"
require_file "EMBEDDING.md" "English embedding developer guide exists"
require_file "EMBEDDING.fr.md" "French embedding developer guide exists"
require_file "examples/embedding/CMakeLists.txt" "standalone embedding example CMake project exists"
require_file "examples/embedding/README.md" "embedding example quick-start exists"
require_file "examples/embedding/01_hello.c" "minimal embedding example exists"
require_file "examples/embedding/02_search_root.c" "search-root embedding example exists"
require_file "examples/embedding/03_values.c" "scalar-value embedding example exists"
require_file "examples/embedding/04_call.c" "direct-call embedding example exists"
require_file "examples/embedding/05_errors.c" "error-recovery embedding example exists"
require_file "examples/embedding/06_lifecycle_threads.c" "lifecycle/threading embedding example exists"
require_file "include/babet/babet.h" "public embedding C header exists"
require_file "src/embedding/babet_c_api.cpp" "embedding C implementation exists"
require_file "tests/embedding_smoke.c" "embedding smoke host is written in C"
require_file "tests/embedding_external_smoke.c" "external standalone SDK smoke host is written in C"
require_file "tools/create_embedding_sdk.sh" "standalone embedding SDK builder exists"
require_file "tools/test_embedding_sdk_builder.sh" "standalone SDK builder regression exists"

require_grep 'static `libbabet\.a`' "EMBEDDING_DESIGN.md" "static-first embedding artifact is explicit"
require_grep 'runtime.*libbabet\.so|libbabet\.so.*dependency' "EMBEDDING_DESIGN.md" "official CLI autonomy is explicit"
require_grep 'exactly one live embedded context' "EMBEDDING_DESIGN.md" "single-context first contract is explicit"
require_grep 'created, used and destroyed by one host thread' "EMBEDDING_DESIGN.md" "same-thread context lifecycle is explicit"
require_grep 'No `lua_State`' "EMBEDDING_DESIGN.md" "Lua internals are excluded from public ABI"
require_grep 'No C\+\+ exception may cross' "EMBEDDING_DESIGN.md" "C exception boundary is explicit"
require_grep 'experimental during Lot 6' "EMBEDDING_DESIGN.md" "public ABI is not frozen prematurely"
require_grep 'exactly one explicit module search root' "EMBEDDING_DESIGN.md" "embedding design defines a single explicit module root"
require_grep 'before its first Lua execution call' "EMBEDDING_DESIGN.md" "embedding design freezes search root before execution"
require_grep 'same absolute root is propagated to workers' "EMBEDDING_DESIGN.md" "embedding design keeps parent and worker module roots aligned"
require_grep 'only five scalar types' "EMBEDDING_DESIGN.md" "embedding design limits first value exchange to scalars"
require_grep 'BABET_STATUS_UNSUPPORTED_VALUE' "EMBEDDING_DESIGN.md" "embedding design rejects unsupported structured values explicitly"
require_grep 'context-owned storage' "EMBEDDING_DESIGN.md" "embedding design defines returned string lifetime"
require_grep 'does not implicitly copy globals into workers' "EMBEDDING_DESIGN.md" "embedding design preserves worker global isolation"
require_grep 'babet_context_call_global\(\)' "EMBEDDING_DESIGN.md" "embedding design defines direct scalar global calls"
require_grep 'requests exactly one result' "EMBEDDING_DESIGN.md" "embedding design fixes one-result call semantics"
require_grep 'missing/non-function global or a Lua exception returns' "EMBEDDING_DESIGN.md" "embedding design classifies bad call targets as Lua errors"
require_grep 'does not resolve dotted method paths' "EMBEDDING_DESIGN.md" "embedding design defers dotted method lookup"
require_grep 'relocatable static SDK' "EMBEDDING_DESIGN.md" "embedding design defines a relocatable standalone SDK"
require_grep 'flattened `libbabet\.a`' "EMBEDDING_DESIGN.md" "embedding design defines a flattened standalone archive"
require_grep 'C\+\+ linker driver' "EMBEDDING_DESIGN.md" "embedding design documents the C++ final-link requirement"

require_grep 'babet_context_create\(\)' "EMBEDDING.md" "English guide documents the minimal lifecycle"
require_grep 'babet_context_set_search_root\(\)' "EMBEDDING.md" "English guide documents search-root use"
require_grep 'BABET_VALUE_STRING' "EMBEDDING.md" "English guide documents scalar values"
require_grep 'borrowed from the context' "EMBEDDING.md" "English guide documents borrowed string lifetime"
require_grep 'babet_context_call_global\(\)' "EMBEDDING.md" "English guide documents direct Lua calls"
require_grep 'BABET_STATUS_BUSY' "EMBEDDING.md" "English guide documents single-context contention"
require_grep 'BABET_STATUS_WRONG_THREAD' "EMBEDDING.md" "English guide documents thread ownership"
require_grep 'objdump -T' "EMBEDDING.md" "English guide documents GLIBC symbol measurement"
require_grep 'not currently promise a fixed `glibc >= X`' "EMBEDDING.md" "English guide avoids a false glibc baseline promise"
require_grep 'babet_context_create\(\)' "EMBEDDING.fr.md" "French guide documents the minimal lifecycle"
require_grep 'babet_context_set_search_root\(\)' "EMBEDDING.fr.md" "French guide documents search-root use"
require_grep 'BABET_VALUE_STRING' "EMBEDDING.fr.md" "French guide documents scalar values"
require_grep 'emprunté au contexte' "EMBEDDING.fr.md" "French guide documents borrowed string lifetime"
require_grep 'babet_context_call_global\(\)' "EMBEDDING.fr.md" "French guide documents direct Lua calls"
require_grep 'BABET_STATUS_BUSY' "EMBEDDING.fr.md" "French guide documents single-context contention"
require_grep 'BABET_STATUS_WRONG_THREAD' "EMBEDDING.fr.md" "French guide documents thread ownership"
require_grep 'objdump -T' "EMBEDDING.fr.md" "French guide documents GLIBC symbol measurement"
require_grep 'ne promet actuellement aucun seuil fixe `glibc >= X`' "EMBEDDING.fr.md" "French guide avoids a false glibc baseline promise"

require_grep 'babet_context_create' "examples/embedding/01_hello.c" "minimal example creates an embedding context"
require_grep 'babet_context_set_search_root' "examples/embedding/02_search_root.c" "search-root example configures a module root"
require_grep "require\('greeting'\)" "examples/embedding/02_search_root.c" "search-root example requires a host module"
require_grep 'BABET_VALUE_STRING' "examples/embedding/03_values.c" "value example sends a binary-safe string"
require_grep 'babet_context_get_global' "examples/embedding/03_values.c" "value example reads a Lua scalar"
require_grep 'babet_context_call_global' "examples/embedding/04_call.c" "call example invokes a Lua global"
require_grep 'BABET_STATUS_LUA_ERROR' "examples/embedding/05_errors.c" "error example checks Lua failure classification"
require_grep 'recovered' "examples/embedding/05_errors.c" "error example proves context recovery"
require_grep 'BABET_STATUS_BUSY' "examples/embedding/06_lifecycle_threads.c" "lifecycle example checks second-context rejection"
require_grep 'BABET_STATUS_WRONG_THREAD' "examples/embedding/06_lifecycle_threads.c" "lifecycle example checks wrong-thread rejection"
require_grep 'BABET_SDK_DIR' "examples/embedding/CMakeLists.txt" "example CMake project consumes the standalone SDK"
require_grep 'LINKER_LANGUAGE CXX' "examples/embedding/CMakeLists.txt" "example CMake project uses a C++ final linker"

require_grep 'typedef struct babet_context babet_context;' "include/babet/babet.h" "public context is opaque"
require_grep 'extern "C"' "include/babet/babet.h" "public header supports C++ hosts through a C ABI"
forbid_grep 'lua_State|std::|#include[[:space:]]*<lua|class[[:space:]]' "include/babet/babet.h" "public header exposes no Lua/C++ implementation type"
require_grep 'BABET_STATUS_BUSY' "include/babet/babet.h" "public status surface represents single-context contention"
require_grep 'BABET_STATUS_WRONG_THREAD' "include/babet/babet.h" "public status surface represents wrong-thread use"
require_grep 'babet_context_set_search_root' "include/babet/babet.h" "public API exposes explicit search-root configuration"
require_grep 'before the first Lua execution call' "include/babet/babet.h" "search-root lifecycle is explicit in public header"
require_grep 'same \?\.lua and \?/init\.lua' "include/babet/babet.h" "public search-root semantics match folder mode"
require_grep 'BABET_STATUS_UNSUPPORTED_VALUE' "include/babet/babet.h" "public status surface represents unsupported Lua values"
require_grep 'typedef enum babet_value_type' "include/babet/babet.h" "public scalar value type is explicit"
require_grep 'BABET_VALUE_NIL' "include/babet/babet.h" "public scalar values include nil"
require_grep 'BABET_VALUE_BOOLEAN' "include/babet/babet.h" "public scalar values include boolean"
require_grep 'BABET_VALUE_INTEGER' "include/babet/babet.h" "public scalar values include signed integer"
require_grep 'BABET_VALUE_NUMBER' "include/babet/babet.h" "public scalar values include number"
require_grep 'BABET_VALUE_STRING' "include/babet/babet.h" "public scalar values include byte string"
require_grep 'int64_t integer' "include/babet/babet.h" "public integer marshalling is explicitly 64-bit"
require_grep 'size_t length' "include/babet/babet.h" "public string marshalling is length-delimited"
require_grep 'babet_context_set_global' "include/babet/babet.h" "public API exposes C-to-Lua scalar globals"
require_grep 'babet_context_get_global' "include/babet/babet.h" "public API exposes Lua-to-C scalar globals"
require_grep 'babet_context_call_global' "include/babet/babet.h" "public API exposes scalar global function calls"
require_grep 'one Lua result is requested' "include/babet/babet.h" "public call API documents one-result semantics"
require_grep 'extra Lua results are discarded' "include/babet/babet.h" "public call API documents extra-result discard"

require_grep 'std::mutex g_context_mutex' "src/embedding/babet_c_api.cpp" "embedding context ownership is serialized"
require_grep 'g_active_context' "src/embedding/babet_c_api.cpp" "embedding enforces one active context"
require_grep 'register_main_thread\(\)' "src/embedding/babet_c_api.cpp" "embedding captures the host owner thread"
require_grep 'register_bundled_modules\(state\)' "src/embedding/babet_c_api.cpp" "embedding installs bundled Lua modules"
require_grep 'register_babet\(state\)' "src/embedding/babet_c_api.cpp" "embedding installs the complete Babet Lua API"
require_grep 'babet_context_set_search_root' "src/embedding/babet_c_api.cpp" "embedding implements explicit search-root configuration"
require_grep 'fs::absolute' "src/embedding/babet_c_api.cpp" "embedding resolves search root to an absolute path"
require_grep 'fs::is_directory' "src/embedding/babet_c_api.cpp" "embedding rejects non-directory search roots"
require_grep 'std::errc::no_such_file_or_directory' "src/embedding/babet_c_api.cpp" "missing search roots are classified as invalid arguments"
require_grep 'std::errc::not_a_directory' "src/embedding/babet_c_api.cpp" "non-directory path errors are classified as invalid arguments"
require_grep 'execution_started' "src/embedding/babet_c_api.cpp" "embedding freezes search root once execution starts"
require_grep 'set_workers_init_context\(std::move\(worker_root\)' "src/embedding/babet_c_api.cpp" "embedding propagates search root to worker initialization"
require_grep 'prepend_babet_package_path\(state, package_prefix\)' "src/embedding/babet_c_api.cpp" "embedding reuses shared protected package-path helper"
require_grep 'value_string_storage' "src/embedding/babet_c_api.cpp" "embedding owns returned scalar string storage"
require_grep 'set_global_thunk' "src/embedding/babet_c_api.cpp" "C-to-Lua scalar emission runs through a protected thunk"
require_grep 'get_global_thunk' "src/embedding/babet_c_api.cpp" "Lua-to-C scalar lookup runs through a protected thunk"
require_grep 'lua_pcall\(context->lua, 1, 0, 0\)' "src/embedding/babet_c_api.cpp" "C-to-Lua scalar mutation catches Lua longjmp failures"
require_grep 'lua_pcall\(context->lua, 1, 1, 0\)' "src/embedding/babet_c_api.cpp" "Lua-to-C scalar lookup catches Lua longjmp failures"
require_grep 'BABET_STATUS_UNSUPPORTED_VALUE' "src/embedding/babet_c_api.cpp" "structured Lua values return explicit unsupported status"
require_grep 'owned_string.assign' "src/embedding/babet_c_api.cpp" "borrowed string round-trip copies input before invalidation"
require_grep 'call_global_thunk' "src/embedding/babet_c_api.cpp" "scalar global calls run through a protected thunk"
require_grep 'lua_call\(state, static_cast<int>\(operation->arguments->size\(\)\), 1\)' "src/embedding/babet_c_api.cpp" "scalar global calls request exactly one Lua result"
require_grep 'owned_arguments.reserve' "src/embedding/babet_c_api.cpp" "call arguments are copied before context invalidation"
require_grep 'read_scalar_result' "src/embedding/babet_c_api.cpp" "global reads and calls share scalar result conversion"
require_grep 'context->execution_started = true' "src/embedding/babet_c_api.cpp" "direct Lua calls freeze the search-root lifecycle"
require_grep 'close_babet_lua_state\(context->lua\)' "src/embedding/babet_c_api.cpp" "embedding uses shared terminal-aware teardown"
require_grep 'catch \(' "src/embedding/babet_c_api.cpp" "C API has explicit C++ exception containment"

forbid_grep '^void register_babet\(' "src/main.cpp" "register_babet implementation no longer lives in CLI main"
require_grep 'runtime_registration\.hpp' "src/main.cpp" "CLI consumes shared runtime registration"
require_grep 'runtime_registration\.hpp' "src/lua_bindings/workers.cpp" "workers consume shared runtime registration"
require_grep '^void register_babet\(' "src/project_core/runtime_registration.cpp" "runtime registration has one reusable implementation"
require_grep '^void close_babet_lua_state\(' "src/project_core/runtime_registration.cpp" "terminal-aware Lua teardown has one reusable implementation"
require_grep '^void prepend_babet_package_path\(' "src/project_core/runtime_registration.cpp" "package-path mutation has one reusable implementation"
require_grep 'prepend_babet_package_path\(state, package_prefix\)' "src/main.cpp" "CLI uses shared package-path helper"
require_grep 'prepend_babet_package_path\(state, package_prefix\)' "src/lua_bindings/workers.cpp" "workers use shared package-path helper"

require_grep 'add_library\(\$\{BABET_RUNTIME_TARGET\} STATIC' "CMakeLists.txt" "CMake builds a static libbabet runtime"
require_grep 'OUTPUT_NAME babet' "CMakeLists.txt" "static runtime artifact is named libbabet"
require_grep 'target_link_libraries\(\$\{PROJECT_NAME\} PRIVATE \$\{BABET_RUNTIME_TARGET\}\)' "CMakeLists.txt" "official CLI links libbabet statically at build time"
forbid_grep 'add_library\([^)]*SHARED' "CMakeLists.txt" "Lot 6 does not introduce a shared libbabet runtime"
require_grep 'add_executable\(babet_embedding_smoke EXCLUDE_FROM_ALL' "CMakeLists.txt" "C smoke host is an explicit non-product build target"
require_grep 'LINKER_LANGUAGE CXX' "CMakeLists.txt" "C host links the C++ runtime with the correct linker driver"

require_grep 'find include -type f -print0' "build_local.sh" "build source fingerprint includes the public embedding header"
require_grep 'create_embedding_sdk\.sh' "build_local.sh" "normal build creates the standalone embedding SDK"
require_grep 'ABSL_STATIC_LIBS' "build_local.sh" "standalone SDK includes pinned Abseil static archives"
require_grep 'SDK embedding autonome : non généré pour le build ASan/UBSan' "build_local.sh" "sanitizer build does not masquerade as a redistributable SDK"
require_grep 'test_embedding_runtime\.sh' "run_tests.sh" "normal validation runs the embedding runtime smoke test"
require_grep 'test_embedding_contracts\.sh' "run_tests.sh" "normal validation runs the embedding structural preflight"
require_grep 'test_embedding_sdk_builder\.sh' "run_tests.sh" "normal validation runs the standalone SDK builder preflight"
require_grep 'EMBEDDING_ARGS\+=\(--sanitizers\)' "run_tests.sh" "sanitizer validation selects the instrumented embedding build"

require_grep 'BABET_STATUS_BUSY' "tests/embedding_smoke.c" "smoke host exercises second-context rejection"
require_grep 'babet\.base64\.encode' "tests/embedding_smoke.c" "smoke host exercises a real Babet binding"
require_grep 'babet\.json\.decode' "tests/embedding_smoke.c" "smoke host exercises a Babet submodule"
require_grep "require\('inspect'\)" "tests/embedding_smoke.c" "smoke host exercises a bundled module"
require_grep "inspect\(\{answer=42\}\)" "tests/embedding_smoke.c" "smoke host functionally exercises bundled inspect module"
require_grep 'babet\.workers\.spawn' "tests/embedding_smoke.c" "smoke host exercises worker runtime reuse"
require_grep 'embedding sentinel' "tests/embedding_smoke.c" "smoke host exercises Lua error diagnostics"
require_grep 'BABET_STATUS_WRONG_THREAD' "tests/embedding_smoke.c" "smoke host exercises wrong-thread rejection"
require_grep 'recreate' "tests/embedding_smoke.c" "smoke host exercises sequential context recreation"
require_grep 'host_module\.lua' "tests/embedding_smoke.c" "smoke host creates an external Lua module fixture"
require_grep 'host_pkg/init\.lua' "tests/embedding_smoke.c" "smoke host creates an init.lua package fixture"
require_grep 'file search root' "tests/embedding_smoke.c" "smoke host rejects an existing regular file as search root"
require_grep 'missing search root' "tests/embedding_smoke.c" "smoke host rejects a missing search root as invalid argument"
require_grep 'babet_context_set_search_root\(context, g_search_root\)' "tests/embedding_smoke.c" "smoke host configures the explicit search root"
require_grep "require\('host_module'\)" "tests/embedding_smoke.c" "main embedded state requires a module from the host root"
require_grep "require\('host_pkg'\)" "tests/embedding_smoke.c" "main embedded state exercises root ?/init.lua semantics"
require_grep 'workers\.spawn.*host_module' "tests/embedding_smoke.c" "worker requires a module from the same host root"
require_grep 'search root after run' "tests/embedding_smoke.c" "smoke host rejects late search-root mutation"
require_grep 'wrong-thread search root' "tests/embedding_smoke.c" "smoke host rejects search-root mutation from another thread"
require_grep 'set host nil' "tests/embedding_smoke.c" "smoke host sends nil from C to Lua"
require_grep 'set host boolean' "tests/embedding_smoke.c" "smoke host sends boolean from C to Lua"
require_grep 'set host integer' "tests/embedding_smoke.c" "smoke host sends integer from C to Lua"
require_grep 'set host number' "tests/embedding_smoke.c" "smoke host sends number from C to Lua"
require_grep 'set host byte string' "tests/embedding_smoke.c" "smoke host sends binary string from C to Lua"
require_grep 'get Lua byte string' "tests/embedding_smoke.c" "smoke host reads binary string from Lua to C"
require_grep 'round-trip borrowed string' "tests/embedding_smoke.c" "smoke host round-trips borrowed binary string safely"
require_grep 'BABET_STATUS_UNSUPPORTED_VALUE' "tests/embedding_smoke.c" "smoke host rejects structured Lua values explicitly"
require_grep 'wrong-thread set global' "tests/embedding_smoke.c" "smoke host rejects C-to-Lua values from wrong thread"
require_grep 'wrong-thread get global' "tests/embedding_smoke.c" "smoke host rejects Lua-to-C values from wrong thread"
require_grep 'call Lua scalar function' "tests/embedding_smoke.c" "smoke host calls Lua with scalar arguments"
require_grep 'function host_scalar_call' "tests/embedding_smoke.c" "smoke host defines the scalar call fixture before invoking it"
require_grep 'function host_no_result' "tests/embedding_smoke.c" "smoke host defines the no-result call fixture"
require_grep 'function host_structured_result' "tests/embedding_smoke.c" "smoke host defines the structured-result call fixture"
require_grep 'function host_call_error' "tests/embedding_smoke.c" "smoke host defines the Lua-error call fixture"
require_grep 'call_arguments\[0\]\.type = BABET_VALUE_NIL' "tests/embedding_smoke.c" "smoke host includes nil in direct call arguments"
require_grep 'get borrowed call string' "tests/embedding_smoke.c" "smoke host copies borrowed call string inputs safely"
require_grep 'X\\0Y\\0R' "tests/embedding_smoke.c" "smoke host checks binary-safe scalar call results"
require_grep 'call Lua no-result function' "tests/embedding_smoke.c" "smoke host maps no-result calls to nil"
require_grep 'reject structured call result' "tests/embedding_smoke.c" "smoke host rejects structured call results"
require_grep 'call missing function' "tests/embedding_smoke.c" "smoke host covers missing call targets"
require_grep 'embedding call sentinel' "tests/embedding_smoke.c" "smoke host covers Lua call errors"
require_grep 'call recovery after Lua error' "tests/embedding_smoke.c" "smoke host proves call recovery after Lua error"
require_grep 'wrong-thread call global' "tests/embedding_smoke.c" "smoke host rejects direct calls from wrong thread"
require_grep 'search root after call' "tests/embedding_smoke.c" "smoke host proves direct calls freeze search-root configuration"

require_grep 'babet-embedding-sdk\.XXXXXX' "tools/create_embedding_sdk.sh" "SDK builder uses a space-free temporary merge workspace"
require_grep 'ADDLIB %04d\.a' "tools/create_embedding_sdk.sh" "SDK builder flattens staged static archives through ar MRI"
require_grep 'include/babet/babet\.h' "tools/create_embedding_sdk.sh" "SDK builder publishes the public header layout"
require_grep 'lib/libbabet\.a' "tools/create_embedding_sdk.sh" "SDK builder publishes one flattened libbabet archive"
require_grep 'EMBEDDING\.fr\.md' "tools/create_embedding_sdk.sh" "SDK builder publishes bilingual developer documentation"
require_grep 'EMBEDDING_DESIGN\.md' "tools/create_embedding_sdk.sh" "SDK builder publishes the embedding design contract"
require_grep 'examples/embedding' "tools/create_embedding_sdk.sh" "SDK builder publishes embedding examples"
require_grep 'project_build_sanitizers' "tools/test_embedding_runtime.sh" "runtime regression targets the sanitizer libbabet build when requested"
require_grep 'sdk moved with spaces' "tools/test_embedding_runtime.sh" "runtime regression relocates the SDK before external linking"
require_grep 'embedding_external_smoke\.c' "tools/test_embedding_runtime.sh" "runtime regression compiles a source-tree-independent external host"
require_grep 'external C host compiles and links using only the moved standalone SDK' "tools/test_embedding_runtime.sh" "runtime regression checks out-of-tree standalone linking"
require_grep 'documentation examples configure and build out of tree' "tools/test_embedding_runtime.sh" "runtime regression builds SDK documentation examples"
require_grep 'documentation examples execute successfully' "tools/test_embedding_runtime.sh" "runtime regression executes SDK documentation examples"
require_grep 'max_glibc_requirement' "tools/test_embedding_runtime.sh" "runtime regression measures GLIBC symbol requirements"
require_grep 'babet_context_call_global' "tests/embedding_external_smoke.c" "external SDK smoke exercises the public scalar call API"
require_grep 'babet\.base64\.encode' "tests/embedding_external_smoke.c" "external SDK smoke exercises a real Babet binding"

echo "embedding structural contracts: ${PASS} PASS / ${FAIL} FAIL"
[ "${FAIL}" -eq 0 ]
